spring:
  application:
    name: service-b

server:
  port: 8082
  servlet:
    context-path: /b

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,metrics

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

service-a-url: http://localhost:8082
