spring:
  application:
    name: service-b
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082
  servlet:
    context-path: /b

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics # default
        step: 10s # default 1m
    tracing:
      endpoint: http://localhost:4318/v1/traces # default
  tracing:
    sampling:
      probability: 1.0 # default 0.1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
