receivers:
  otlp:
    protocols:
      grpc:

connectors:
  servicegraph:

processors:
  # batch metrics before sending to reduce API usage
  resource:
    attributes:
    - action: insert
      key: loki.format
      value: logfmt
    - action: insert
      key: loki.resource.labels
      value: service.name, container.id
  batch:

  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(metric.description, "")
      - context: datapoint
        statements:
          - set(attributes["instance"], resource.attributes["container.id"])
          - set(attributes["application"], resource.attributes["service.name"])
#          - set(attributes["application"], attributes["main_application_class"])

#      - context: metric
#        statements:
#          - set(description, "Yyy") where name == "http.server.requests"
#      - context: datapoint
#        statements:
#          - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
#          - set(attributes["container"], resource.attributes["k8s.container.name"])
#          - set(attributes["pod"], resource.attributes["k8s.pod.name"])

exporters:
  logging:
    loglevel: debug

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheus:
    endpoint: ":8889"
    const_labels:
      source: otel-collector

# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
    endpoint: :1888
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:
    endpoint: 0.0.0.0:55679


service:
  extensions: [ health_check, pprof, zpages ]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, servicegraph ]
    metrics:
      receivers: [ otlp, servicegraph ]
      processors: [ transform,batch ]
      exporters: [ logging,prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ loki ]
