receivers:
  otlp:
    protocols:
      http:
      grpc:


processors:
  # batch metrics before sending to reduce API usage
  batch:

  # Define the attributes processor to modify the help text for specific metrics
  #  attributes/delete_help:
  #    actions:
  #      # Modify the help text for http_server_requests_seconds and http_server_requests_seconds_max metrics
  #      - key: http_server_requests_seconds
  #        action: delete
  #      - key: http_server_requests_max_seconds
  #        action: delete

  transform:
    metric_statements:
      - context: metric
        statements:
          - set(description, "Zzz") where name == "http.server.requests.max"
      - context: metric
        statements:
          - set(description, "Yyy") where name == "http.server.requests"
#      - context: datapoint
#        statements:
#          - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
#          - set(attributes["container"], resource.attributes["k8s.container.name"])
#          - set(attributes["pod"], resource.attributes["k8s.pod.name"])

exporters:
  logging:
    loglevel: debug

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheus:
    endpoint: ":8889"
    const_labels:
      source: otel-collector

# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:
    endpoint: 0.0.0.0:55679


service:
  extensions: [ health_check, pprof, zpages ]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp ]
    metrics:
      receivers: [ otlp ]
      processors: [ transform,batch ]
      exporters: [ prometheus ]
