spring:
  application:
    name: service-a

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

#  sleuth:
#    otel:
#      config:
#        trace-id-ratio-based: 1.0
#      exporter:
#        otlp:
#          endpoint: http://localhost:4317
#    #    trace-id128: true
#    propagation:
#      type: w3c
  #    supports-join: false

server:
  port: 8081
  servlet:
    context-path: /a