spring:
  application:
    name: service-a

server:
  port: 8081
  servlet:
    context-path: /a

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
